name: ai_ready_data_pipeline
version: "1.0.0"
config-version: 2

profile: ai_ready_data_pipeline

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ai_ready_data_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
